In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from scipy.spatial import distance

In [2]:
data = pd.read_csv(r"E:\Summer training 2025\SpotifyFeatures.csv")
data.head()

,genre,artist_name,track_name,track_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,Movie,Henri Salvador,C'est beau de faire un Show,0BRjO6ga9RKCKjfDqeFgWV,0,0.611,0.389,99373,0.910,0.000,C#,0.3460,-1.828,Major,0.0525,166.969,4/4,0.814
1,Movie,Martin & les fées,Perdu d'avance (par Gad Elmaleh),0BjC1NfoEOOusryehmNudP,1,0.246,0.590,137373,0.737,0.000,F#,0.1510,-5.559,Minor,0.0868,174.003,4/4,0.816
2,Movie,Joseph Williams,Don't Let Me Be Lonely Tonight,0CoSDzoNIKCRs124s9uTVy,3,0.952,0.663,170267,0.131,0.000,C,0.1030,-13.879,Minor,0.0362,99.488,5/4,0.368
3,Movie,Henri Salvador,Dis-moi Monsieur Gordon Cooper,0Gc6TVm52BwZD07Ki6tIvf,0,0.703,0.240,152427,0.326,0.000,C#,0.0985,-12.178,Major,0.0395,171.758,4/4,0.227
4,Movie,Fabien Nataf,Ouverture,0IuslXpMROHdEPvSl1fTQK,4,0.950,0.331,82625,0.225,0.123,F,0.2020,-21.150,Major,0.0456,140.576,4/4,0.390

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232725 entries, 0 to 232724
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   genre             232725 non-null  object
 1   artist_name       232725 non-null  object
 2   track_name        232724 non-null  object
 3   track_id          232725 non-null  object
 4   popularity        232725 non-null  int64
 5   acousticness      232725 non-null  float64
 6   danceability      232725 non-null  float64
 7   duration_ms       232725 non-null  int64
 8   energy            232725 non-null  float64
 9   instrumentalness  232725 non-null  float64
 10  key               232725 non-null  object
 11  liveness          232725 non-null  float64
 12  loudness          232725 non-null  float64
 13  mode              232725 non-null  object
 14  speechiness       232725 non-null  float64
 15  tempo             232725 non-null  float64
 16  time_signature    232725 non-null  object
 17  valence           232725 non-null  float64
dtypes: float64(9), int64(2), object(7)
memory usage: 32.0+ MB

In [6]:
data = data.drop(["track_id", "key", "mode", "time_signature"], axis=1)
df = data.copy()
df = df.drop(["artist_name", "track_name"], axis=1)

In [7]:
col = ['popularity', 'acousticness', 'danceability', 'duration_ms',
       'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness',
       'tempo', 'valence']
scaler = StandardScaler()
df[col] = scaler.fit_transform(df[col])

In [9]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
enc = pd.DataFrame(encoder.fit_transform(np.array(df["genre"]).reshape(-1, 1)))
enc.columns = encoder.get_feature_names_out(["genre"])

In [10]:
enc.head()

,genre_A Capella,genre_Alternative,genre_Anime,genre_Blues,genre_Children's Music,genre_Children’s Music,genre_Classical,genre_Comedy,genre_Country,genre_Dance,...,genre_Pop,genre_R&B,genre_Rap,genre_Reggae,genre_Reggaeton,genre_Rock,genre_Ska,genre_Soul,genre_Soundtrack,genre_World
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
df[enc.columns] = enc
df = df.drop("genre", axis=1)
df.head()

,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,...,genre_Pop,genre_R&B,genre_Rap,genre_Reggae,genre_Reggaeton,genre_Rock,genre_Ska,genre_Soul,genre_Soundtrack,genre_World
0,-2.261007,0.683376,-0.890935,-1.141368,1.286908,-0.489819,0.660661,1.290703,-0.367970,1.595607,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-2.206031,-0.345467,0.191994,-0.821867,0.630249,-0.489819,-0.322835,0.668683,-0.183082,1.823253,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-2.096080,1.644570,0.585296,-0.545298,-1.669954,-0.489819,-0.564927,-0.718402,-0.455832,-0.588326,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-2.261007,0.942701,-1.693703,-0.695295,-0.929789,-0.489819,-0.587623,-0.434817,-0.438044,1.750597,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-2.041104,1.638932,-1.203422,-1.282184,-1.313157,-0.083566,-0.065613,-1.930601,-0.405163,0.741433,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
df["name"] = data["track_name"]
df["artist"] = data["artist_name"]

df_2 = df.drop(["artist", "name"], axis=1)

In [17]:
def find_song(word, artist):
    b = 0
    for a in range(len(data)):
        track = str(data["track_name"][a]).lower()
        singer = str(data["artist_name"][a]).lower()
        if word.lower() in track and artist.lower() in singer:
            print("Song Name:", data["track_name"][a], ", Artist:", data["artist_name"][a])
            b += 1
    if b == 0:
        print("No match found.")

In [18]:
word = "ocean eyes"
artist = "billie"

find_song(word,artist)

Song Name: ocean eyes , Artist: Billie Eilish
Song Name: Ocean Eyes - Blackbear Remix , Artist: Billie Eilish
Song Name: Ocean Eyes - Astronomyy Remix , Artist: Billie Eilish
Song Name: Ocean Eyes - GOLDHOUSE Remix , Artist: Billie Eilish

In [28]:
def sim_track_find(word, artist):
    song = []
    indexes = []
    for a in range(len(data)):
        track = str(data["track_name"][a]).lower()
        singer = str(data["artist_name"][a]).lower()
        if word.lower() in track and artist.lower() in singer:
            song.append(df_2[a:a+1].values)
            indexes.append(a)

    if len(song) == 0:
        print("No matching songs found.")
        return [], []
    else:
        print(f"Found {len(song)} song(s):")
        for idx in indexes:
            print("Song Name:", data["track_name"][idx], ", Artist:", data["artist_name"][idx])
        return song, indexes

In [29]:
word = "ocean eyes"
artist = "billie"

sim_track_find(word,artist)

Found 4 song(s):
Song Name: ocean eyes , Artist: Billie Eilish
Song Name: Ocean Eyes - Blackbear Remix , Artist: Billie Eilish
Song Name: Ocean Eyes - Astronomyy Remix , Artist: Billie Eilish
Song Name: Ocean Eyes - GOLDHOUSE Remix , Artist: Billie Eilish

([array([[ 2.46688968,  1.2612199 , -0.23363492, -0.29211879, -0.789348  ,
          -0.38511779, -0.66075482,  0.32007742, -0.42995857,  0.88111447,
          -1.09940568,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ]]),
  array([[ 1.91713431, -0.70344834,  0.54219444, -0.3347637 , -0.50466939,
          -0.48977393, -0.63402389, -0.05353524, -0.40570215,  0.88418902,
          -1.28012978,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ]]),
  array([[ 1.80718323,  0.78485127,  0.15427976,  0.51409866, -0.37181938,
          -0.46207448, -0.60224938,  0.15719497, -0.46014434,  0.88253847,
          -1.51545563,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ]]),
  array([[ 1.53230554, -0.95065265, -0.67003893, -0.18095784,  1.4577151 ,
           0.23020541,  0.16134749,  1.1771692 , -0.44559049,  2.66192565,
           0.43867178,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ]])],
 [107896, 108497, 108942, 110728])

In [30]:
from scipy.spatial import distance

def similar_tracks(data, number, song="", artist=""):
    songs, indexes = sim_track_find(song, artist)
    if not songs:
        return 0

    x = songs[0].flatten()   # the first matched track's features
    index = indexes[0]

    p = []
    for count, i in enumerate(df_2.values):
        if count == index:
            continue  # skip the same song
        dist = distance.cosine(x, i)
        p.append((dist, count))

    p.sort()

    song_names = df["name"]
    artist_names = df["artist"]

    print("\nSimilar songs to", song_names[index], "by", artist_names[index], ":\n")
    for i in range(min(number, len(p))):
        print(f"{i+1} - {song_names[p[i][1]]}, {artist_names[p[i][1]]}")

In [31]:
song = "ocean eyes"
artist = "billie"
num = 5

similar_tracks(df,int(num),song,artist)

Found 4 song(s):
Song Name: ocean eyes , Artist: Billie Eilish
Song Name: Ocean Eyes - Blackbear Remix , Artist: Billie Eilish
Song Name: Ocean Eyes - Astronomyy Remix , Artist: Billie Eilish
Song Name: Ocean Eyes - GOLDHOUSE Remix , Artist: Billie Eilish

Similar songs to ocean eyes by Billie Eilish :

1 - Abrázame Muy Fuerte, Juan Gabriel
2 - I Can't Fall in Love Without You, Zara Larsson
3 - idontwannabeyouanymore, Billie Eilish
4 - Make It To Me, Sam Smith
5 - Let It Go, James Bay